### ISSUE TITLE
Git installation on Mac OS X 10.6.8 Snow Leopard

### ISSUE THREAD

**Issue by christianbundy** [fraction/news#125]
The only version of git that @rthrblck and I could find that worked with OS X 10.6.8 was Git 1.8.4.2, which we downloaded from [Google Code](https://git-osx-installer.googlecode.com/files/git-1.8.4.2-intel-universal-snow-leopard.dmg) ([mirror](https://web.archive.org/web/20160115170337/https://git-osx-installer.googlecode.com/files/git-1.8.4.2-intel-universal-snow-leopard.dmg)).

Every other version of git would and throw "Illegal instruction" error, like so:

``` sh
$ git --version
Illegal instruction
```

I'll close this issue immediately (as it's already been solved), but I wanted to document which version of git works on Mac OS X 10.6.8 Snow Leopard for anyone else who might be trying to get either Fraction News or git installed.

P.S. I doubt that both Google Code and Wayback Machine are going down anytime soon, but on the off chance that we ever get a content addressable network running, the SHA1 should look something like `07fa2a458ab13e4eb3ff396dd1c713320a281a6b`.

**Comment by cerendundar** [comment]
my mac ox 10.6.8 also throw illegal instruction error with this download. `no option left?

**Comment by christianbundy** [comment]
@cerendundar I'd suggest that you try other downloads from [this list](http://sourceforge.net/projects/git-osx-installer/files/), but I don't have any other solution (or a way to test anything out for you).

If you can't get your development environment working locally, I'd encourage you to try out a VPS [like [DigitalOcean](https://www.digitalocean.com/)) and work via SSH. [iTerm2](http://iterm2.com/) and [Mosh](https://mosh.mit.edu/) are both great, if you can get them installed.

**Comment by junkieslang** [comment]
it still worked in my snow leopard 10.6.8

**Comment by klezmen** [comment]
Im offended github shut us out so easily. Come on guys, developpers can't move so fast with the changes.

**Comment by violapinzi** [comment]
Thank you! It worked also for me!

**Comment by MaximProshin** [comment]
It really works! Thanks Christian!

**Comment by ramanandshukla** [comment]
Thanks it helped

**Comment by krawster** [comment]
Thanks, it's a really worked!

**Comment by dubbsdubblin** [comment]
Hi, I have downloaded the DMG and run that, but then what do I do to use GitHub Desktop??? There appears to be no program installed following running the installation DMG program???

**Comment by christianbundy** [comment]
@dubbsdubblin You're totally right. This is a [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) for Git (instead of a [GUI](https://en.wikipedia.org/wiki/Graphical_user_interface), so you'd have to use a terminal emulator (like [Terminal](https://en.wikipedia.org/wiki/Terminal_%28OS_X%29) or [iTerm2](https://www.iterm2.com/)).

Unfortunately, it looks like GitHub Desktop has never supported any version of OS X lower than 10.7, so using it on Snow Leopard is most likely out of the picture.

**Comment by dubbsdubblin** [comment]
OK thanks

**Comment by smcinerney** [comment]
I think git-2.3.5-intel-universal-snow-leopard.dmg works for OSX 10.6/7/8

**Comment by JeffAbney** [comment]
The mirror link still works and I can use git on my machine now!
