### ISSUE TITLE
Mac OS x 10.6.8

### ISSUE THREAD

**Issue by tamilmunusamy** [fraction/news#155]
Which version of git is suitable for Mac OS x 10.6.8.? I have installed git 2.16.2 version its shows "illegal instruction".

**Comment by christianbundy** [comment]
Hey @tamilmunusamy! The only version I've seen working is Git 1.8.4.2, although [I've read](https://github.com/fraction/news/issues/125#issuecomment-282186303) that Git 2.3.5 may work as well.

Please check out #125 for more info.

**Comment by tamilmunusamy** [comment]
Thanks for your help @christianbundy ... I have downloaded the git from  [https://mackyle.github.io/git-osx-installer/](https://mackyle.github.io/git-osx-installer/)   It's working fine.
